import AppBar from "@components/appbar/app-bar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ActivityProvider } from "@/presentation/providers/activity_provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ActivityProvider>
      <html lang="en">
        <body className={inter.className}>
          <AppBar />
          {/* <AppDrawer /> */}
          {children}
        </body>
      </html>
    </ActivityProvider>
  );
}
